[manager]
prepend_keymap = [
    # Remap Enter to act like 'l'
    { on = [ '<Enter>' ],   run = 'enter', desc = 'Enter the child directory' },
    # Remap Backspace to act like 'h'
    { on = [ '<Backspace>' ], run = 'leave', desc = 'Leave the child directory' },
    # Remap Shift+Enter to act like Enter
    { on = [ '<S-Enter>' ], run = 'open', desc = 'Open file or enter directory' },
]
