# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# kanso with ink colors
# Original: https://github.com/956MB/kanso.yazi/blob/main/themes/kanso/
#
# ...

[colors]
background = "#1F1F1F"
foreground = "#CDCDCD"  # inkWhite
selection = "#7289b6"   # inkViolet
cursor = "#a2aaa1"      # inkGray
black = "#000000"
red = "#e03c30"         # inkRed
green = "#6eb575"       # inkGreen
yellow = "#d9af54"      # inkYellow
blue = "#71a7c1"        # inkBlue2
magenta = "#a784ab"     # inkPink
cyan = "#7ab0a8"        # inkAqua
white = "#CDCDCD"       # inkWhite
bright_black = "#868686"  # inkGray2
bright_red = "#e03c30"    # inkRed
bright_green = "#83a765"  # inkGreen2
bright_yellow = "#d9af54" # inkYellow
bright_blue = "#7c98c7"   # inkTeal
bright_magenta = "#a784ab"  # inkPink
bright_cyan = "#7ab0a8"    # inkAqua
bright_white = "#FFFFFF"

[manager]
cwd = { fg = "cyan" }
# Hovered
hovered         = { fg = "#CDCDCD", bg = "#7289b6" }  # inkWhite, inkViolet
preview_hovered = { underline = true }
# Find
find_keyword  = { fg = "#d9af54", bold = true, italic = true, underline = true }  # inkYellow
find_position = { fg = "#a784ab", bg = "#1F1F1F", bold = true, italic = true }    # inkPink
# Marker
marker_copied   = { fg = "#6eb575", bg = "#6eb575" }  # inkGreen
marker_cut      = { fg = "#e03c30", bg = "#e03c30" }  # inkRed
marker_marked   = { fg = "#7ab0a8", bg = "#7ab0a8" }  # inkAqua
marker_selected = { fg = "#d9af54", bg = "#d9af54" }  # inkYellow
# Tab
tab_active   = { fg = "#CDCDCD", bg = "#1F1F1F" }  # inkWhite
tab_inactive = { fg = "#CDCDCD", bg = "#2D2D2D" }  # inkWhite
tab_width    = 1
# Count
count_copied   = { fg = "#1F1F1F", bg = "#6eb575" }  # inkGreen
count_cut      = { fg = "#1F1F1F", bg = "#e03c30" }  # inkRed
count_selected = { fg = "#1F1F1F", bg = "#d9af54" }  # inkYellow
# Border
border_symbol = "│"
border_style  = { fg = "#6B6B6B" }  # inkGray3
# Highlighting
syntect_theme = "./tmtheme.xml"
# Cursor
cursor_symbol = "█"
cursor = { fg = "#1F1F1F", bg = "#a2aaa1" }  # inkGray
# Executable
exe_symbol = ""
exe = { fg = "#7ab0a8", bg = "#1F1F1F" }  # inkAqua
# Regular
file_symbol = ""
file = { }
# Directory
folder_symbol = ""
folder = { fg = "#71a7c1", bg = "#1F1F1F" }  # inkBlue2
# Hidden
hidden_symbol = ""
hidden = { fg = "#868686" }  # inkGray2
# Link
link_symbol = ""
link = { fg = "#7ab0a8", bg = "#1F1F1F" }  # inkAqua
# Link (broken)
broken_symbol = ""
broken = { fg = "#e03c30", bg = "#3A1212" }  # inkRed
# Selected
selected = { fg = "#FFFFFF", bg = "#7289b6" }  # inkViolet

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#6B6B6B", bg = "#6B6B6B" }  # inkGray3
# Mode
mode_normal = { fg = "#1F1F1F", bg = "#71a7c1", bold = true }  # inkBlue2
mode_select = { fg = "#1F1F1F", bg = "#d9af54", bold = true }  # inkYellow
mode_unset  = { fg = "#1F1F1F", bg = "#e03c30", bold = true }  # inkRed
# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#71a7c1", bg = "#1F1F1F" }  # inkBlue2
progress_error  = { fg = "#e03c30", bg = "#1F1F1F" }  # inkRed
# Permissions
permissions_t = { fg = "#6eb575" }  # inkGreen
permissions_r = { fg = "#d9af54" }  # inkYellow
permissions_w = { fg = "#e03c30" }  # inkRed
permissions_x = { fg = "#7ab0a8" }  # inkAqua
permissions_s = { fg = "#868686" }  # inkGray2

[select]
border   = { fg = "#71a7c1" }  # inkBlue2
active   = { fg = "#a784ab", bold = true }  # inkPink
inactive = {}

[input]
border   = { fg = "#71a7c1" }  # inkBlue2
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#71a7c1" }  # inkBlue2
active   = { bg = "#7289b6" }  # inkViolet
inactive = {}
# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#71a7c1" }  # inkBlue2
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#1F1F1F" }
cand            = { fg = "#7ab0a8" }  # inkAqua
rest            = { fg = "#868686" }  # inkGray2
desc            = { fg = "#a784ab" }  # inkPink
separator       = "  "
separator_style = { fg = "#868686" }  # inkGray2

[help]
on      = { fg = "#7ab0a8" }  # inkAqua
run     = { fg = "#a784ab" }  # inkPink
desc    = { fg = "#CDCDCD" }  # inkWhite
hovered = { bg = "#7289b6", bold = true }  # inkViolet
footer  = { fg = "#CDCDCD", bg = "#252526" }  # inkWhite

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#d9af54" },  # inkYellow
    # Videos
    { mime = "video/*", fg = "#a784ab" },  # inkPink
    # Audio
    { mime = "audio/*", fg = "#a784ab" },  # inkPink
    # Archives
    { mime = "application/zip", fg = "#e03c30" },  # inkRed
    { mime = "application/gzip", fg = "#e03c30" },  # inkRed
    { mime = "application/x-tar", fg = "#e03c30" },  # inkRed
    { mime = "application/x-bzip", fg = "#e03c30" },  # inkRed
    { mime = "application/x-bzip2", fg = "#e03c30" },  # inkRed
    { mime = "application/x-7z-compressed", fg = "#e03c30" },  # inkRed
    { mime = "application/x-rar", fg = "#e03c30" },  # inkRed
    # Documents
    { mime = "application/pdf", fg = "#7ab0a8" },  # inkAqua
    { mime = "application/msword", fg = "#7ab0a8" },  # inkAqua
    { mime = "application/vnd.openxmlformats-officedocument.*", fg = "#7ab0a8" },  # inkAqua
    # Fallback
    { name = "*", fg = "#CDCDCD" },  # inkWhite
    { name = "*/", fg = "#71a7c1" },  # inkBlue2
    # Executable
    { name = "*", category = "executable", fg = "#7ab0a8", bg = "#1F1F1F" },  # inkAqua
    # Directories
    { name = "*/", fg = "#71a7c1", bg = "#1F1F1F" },  # inkBlue2
    # Hidden files
    { name = ".*", fg = "#868686" },  # inkGray2
    # Symlinks
    { name = "*", category = "link", fg = "#7ab0a8", bg = "#1F1F1F" },  # inkAqua
    # Broken symlinks
    { name = "*", category = "broken", fg = "#e03c30", bg = "#3A1212" },  # inkRed
]

[icon]
rules = [
    { name = "Desktop", text = "" },
    { name = "Documents", text = "" },
    { name = "Downloads", text = "" },
    { name = "Pictures", text = "" },
    { name = "Music", text = "" },
    { name = "Videos", text = "" },
    { name = ".git", text = "" },
    { name = ".config", text = "" },
]
