complete -c ocw -f -a status       -d "Show service status"
complete -c ocw -f -a start        -d "Start the service"
complete -c ocw -f -a stop         -d "Stop the service"
complete -c ocw -f -a restart      -d "Restart the service"
complete -c ocw -f -a enable       -d "Enable the service"
complete -c ocw -f -a disable      -d "Disable the service"
complete -c ocw -f -a log          -d "Tail service logs"
complete -c ocw -f -a url          -d "Print Tailscale URL"
complete -c ocw -f -a install      -d "Install and start the service"
complete -c ocw -f -a uninstall    -d "Stop and remove the service"
